In [62]:
import pandas as pd
import numpy as np

In [64]:
df = pd.read_csv("C:\\Users\\aseks\\Downloads\\Binance_BTCUSDT_2024_minute.csv")

In [66]:
df.head()

Unix                 Date   Symbol      Open      High      Low  \
0  1722383940000  2024-07-30 23:59:00  BTCUSDT  66196.00  66196.00  66188.0   
1  1722383880000  2024-07-30 23:58:00  BTCUSDT  66224.00  66224.01  66196.0   
2  1722383820000  2024-07-30 23:57:00  BTCUSDT  66224.01  66224.01  66224.0   
3  1722383760000  2024-07-30 23:56:00  BTCUSDT  66236.01  66240.01  66224.0   
4  1722383700000  2024-07-30 23:55:00  BTCUSDT  66243.99  66244.00  66236.0   

      Close  Volume BTC    Volume USDT  tradecount  
0  66188.00     1.15863   76691.239749         201  
1  66196.00     1.95432  129392.697341         420  
2  66224.01     2.04784  135616.169898         139  
3  66224.01     1.92365  127407.013204         369  
4  66236.01     1.76886  117163.812182         165

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271971 entries, 0 to 271970
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   Unix         271971 non-null  int64  
 1   Date         271971 non-null  object 
 2   Symbol       271971 non-null  object 
 3   Open         271971 non-null  float64
 4   High         271971 non-null  float64
 5   Low          271971 non-null  float64
 6   Close        271971 non-null  float64
 7   Volume BTC   271971 non-null  float64
 8   Volume USDT  271971 non-null  float64
 9   tradecount   271971 non-null  int64  
dtypes: float64(6), int64(2), object(2)
memory usage: 20.7+ MB


In [70]:
df.describe()

Unix           Open           High            Low  \
count  2.719710e+05  271971.000000  271971.000000  271971.000000   
mean   1.712990e+12   59651.542412   59673.910973   59628.781010   
std    5.278070e+09    9677.094722    9681.532535    9672.446114   
min    1.704067e+12   38558.920000   38578.610000   38555.000000   
25%    1.708495e+12   51729.795000   51742.000000   51717.105000   
50%    1.712578e+12   63277.020000   63306.010000   63249.850000   
75%    1.717956e+12   67090.585000   67120.350000   67060.025000   
max    1.722384e+12   73775.550000   73777.000000   73682.610000   

               Close     Volume BTC   Volume USDT     tradecount  
count  271971.000000  271971.000000  2.719710e+05  271971.000000  
mean    59651.622015      26.632802  1.582119e+06    1214.122958  
std      9677.006502      41.288491  2.462690e+06    1502.576150  
min     38558.920000       0.078720  5.071142e+03      60.000000  
25%     51729.825000       7.748540  4.502660e+05     504.000000  
50%     63277.030000      15.304840  8.907286e+05     821.000000  
75%     67090.765000      30.142110  1.779332e+06    1387.000000  
max     73775.540000    1598.537150  7.740024e+07   59520.000000

In [72]:
missing_values = df.isnull().sum()
print("Missing values in each column:\n", missing_values)
numeric_columns = df.select_dtypes(include=[np.number]).columns
df[numeric_columns] = df[numeric_columns].fillna(df[numeric_columns].median())
print(df.head())

Missing values in each column:
 Unix           0
Date           0
Symbol         0
Open           0
High           0
Low            0
Close          0
Volume BTC     0
Volume USDT    0
tradecount     0
dtype: int64
            Unix                 Date   Symbol      Open      High      Low  \
0  1722383940000  2024-07-30 23:59:00  BTCUSDT  66196.00  66196.00  66188.0   
1  1722383880000  2024-07-30 23:58:00  BTCUSDT  66224.00  66224.01  66196.0   
2  1722383820000  2024-07-30 23:57:00  BTCUSDT  66224.01  66224.01  66224.0   
3  1722383760000  2024-07-30 23:56:00  BTCUSDT  66236.01  66240.01  66224.0   
4  1722383700000  2024-07-30 23:55:00  BTCUSDT  66243.99  66244.00  66236.0   

      Close  Volume BTC    Volume USDT  tradecount  
0  66188.00     1.15863   76691.239749         201  
1  66196.00     1.95432  129392.697341         420  
2  66224.01     2.04784  135616.169898         139  
3  66224.01     1.92365  127407.013204         369  
4  66236.01     1.76886  117163.812182       

In [15]:
df = df.drop(columns=['Symbol', 'Unix'])

In [74]:
df['Date'] = pd.to_datetime(df['Date'])

df = df[(df['Date'].dt.month >= 5) & (df['Date'].dt.month <= 7)]

In [19]:
numeric_columns = df.select_dtypes(include=[np.number]).columns

Q1 = df[numeric_columns].quantile(0.25)
Q3 = df[numeric_columns].quantile(0.75)
IQR = Q3 - Q1

df = df[~((df[numeric_columns] < (Q1 - 1.5 * IQR)) | (df[numeric_columns] > (Q3 + 1.5 * IQR))).any(axis=1)]

In [76]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df.loc[:, numeric_columns] = scaler.fit_transform(df[numeric_columns])
print(df.head())

       Unix                Date   Symbol      Open      High       Low  \
0  1.619028 2024-07-30 23:59:00  BTCUSDT  0.539665  0.535143  0.542216   
1  1.619001 2024-07-30 23:58:00  BTCUSDT  0.546810  0.542297  0.544256   
2  1.618975 2024-07-30 23:57:00  BTCUSDT  0.546813  0.542297  0.551397   
3  1.618948 2024-07-30 23:56:00  BTCUSDT  0.549875  0.546383  0.551397   
4  1.618921 2024-07-30 23:55:00  BTCUSDT  0.551912  0.547402  0.554457   

      Close  Volume BTC  Volume USDT  tradecount  
0  0.537628   -0.539953    -0.550166   -0.604011  
1  0.539670   -0.515870    -0.524467   -0.437460  
2  0.546817   -0.513040    -0.521432   -0.651163  
3  0.546817   -0.516798    -0.525436   -0.476246  
4  0.549880   -0.521483    -0.530430   -0.631389  


C:\Users\aseks\AppData\Local\Temp\ipykernel_9928\4207337138.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 1.61902823  1.6190014   1.61897458 ... -1.89579115 -1.89581797
 -1.8958448 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, numeric_columns] = scaler.fit_transform(df[numeric_columns])
C:\Users\aseks\AppData\Local\Temp\ipykernel_9928\4207337138.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.60401109 -0.43745973 -0.65116262 ... -0.15759259 -0.01309597
 -0.16976073]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, numeric_columns] = scaler.fit_transform(df[numeric_columns])


In [78]:
numeric_columns = df.select_dtypes(include=[np.number]).columns
df[numeric_columns] = df[numeric_columns].fillna(df[numeric_columns].median())
df.tail()

Unix                Date   Symbol      Open      High       Low  \
103603 -1.895738 2024-05-01 00:05:00  BTCUSDT -0.865800 -0.861308 -0.864892   
103604 -1.895764 2024-05-01 00:04:00  BTCUSDT -0.860296 -0.861308 -0.860203   
103605 -1.895791 2024-05-01 00:03:00  BTCUSDT -0.868418 -0.865915 -0.863564   
103606 -1.895818 2024-05-01 00:02:00  BTCUSDT -0.848070 -0.853679 -0.863566   
103607 -1.895845 2024-05-01 00:01:00  BTCUSDT -0.852035 -0.848150 -0.851693   

           Close  Volume BTC  Volume USDT  tradecount  
103603 -0.855692    0.124375     0.096405   -0.055684  
103604 -0.865797    0.262649     0.231712   -0.117286  
103605 -0.860293   -0.302382    -0.320958   -0.157593  
103606 -0.868416    0.592466     0.554820   -0.013096  
103607 -0.848070   -0.102069    -0.124645   -0.169761

In [80]:
df['Date'] = pd.to_datetime(df['Date'])
df = df[(df['Date'].dt.month >= 5) & (df['Date'].dt.month <= 7)]

# Step 3: Handle missing values
numeric_columns = df.select_dtypes(include=[np.number]).columns
df[numeric_columns] = df[numeric_columns].fillna(df[numeric_columns].median())

# Step 4: Remove outliers using the IQR method
Q1 = df[numeric_columns].quantile(0.25)
Q3 = df[numeric_columns].quantile(0.75)
IQR = Q3 - Q1
df = df[~((df[numeric_columns] < (Q1 - 1.5 * IQR)) | (df[numeric_columns] > (Q3 + 1.5 * IQR))).any(axis=1)]


In [82]:
scaler = StandardScaler()
df.loc[:, numeric_columns] = scaler.fit_transform(df[numeric_columns])

df['Day_of_Week'] = df['Date'].dt.dayofweek
df['Hour'] = df['Date'].dt.hour
df = df.drop(columns=['Date'])

X = df.drop(columns=['Close'])
y = df['Close']

non_numeric_columns = X.select_dtypes(include=['object', 'datetime', 'datetime64']).columns
X = X.drop(columns=non_numeric_columns)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [84]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

In [86]:
rf = RandomForestRegressor(random_state=42)

param_dist = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, 30, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'max_features': ['sqrt', 'log2']
}

random_search = RandomizedSearchCV(estimator=rf, param_distributions=param_dist, 
                                   n_iter=10, cv=2, verbose=2, random_state=42, n_jobs=-1)

X_train_sample, _, y_train_sample, _ = train_test_split(X_train, y_train, test_size=0.5, random_state=42)

random_search.fit(X_train_sample, y_train_sample)

Fitting 2 folds for each of 10 candidates, totalling 20 fits


RandomizedSearchCV(cv=2, estimator=RandomForestRegressor(random_state=42),
                   n_jobs=-1,
                   param_distributions={'max_depth': [10, 20, 30, None],
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_leaf': [1, 2],
                                        'min_samples_split': [2, 5],
                                        'n_estimators': [100, 200, 300]},
                   random_state=42, verbose=2)

In [88]:
print("Best parameters found: ", random_search.best_params_)
best_rf = random_search.best_estimator_
y_pred = best_rf.predict(X_test)

print("Mean Squared Error: ", mean_squared_error(y_test, y_pred))
print("R2 Score: ", r2_score(y_test, y_pred))

Best parameters found:  {'n_estimators': 200, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': None}
Mean Squared Error:  1.869418083605708e-05
R2 Score:  0.999981374258751


In [96]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
import pandas as pd

y_binned = pd.cut(y, bins=3, labels=["Low", "Medium", "High"])

X_train, X_test, y_train, y_test = train_test_split(X, y_binned, test_size=0.2, random_state=42)

rf_classifier = RandomForestClassifier(random_state=42)

rf_classifier.fit(X_train, y_train)

y_pred = rf_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.9989056087551299
Confusion Matrix:
 [[7219    0    4]
 [   0 2689    4]
 [   7    5 8347]]
Classification Report:
               precision    recall  f1-score   support

        High       1.00      1.00      1.00      7223
         Low       1.00      1.00      1.00      2693
      Medium       1.00      1.00      1.00      8359

    accuracy                           1.00     18275
   macro avg       1.00      1.00      1.00     18275
weighted avg       1.00      1.00      1.00     18275



In [98]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
y_train_numeric = label_encoder.fit_transform(y_train)
y_test_numeric = label_encoder.transform(y_test)
from sklearn.ensemble import RandomForestRegressor

rf_regressor = RandomForestRegressor(random_state=42)

rf_regressor.fit(X_train, y_train_numeric)

y_pred = rf_regressor.predict(X_test)

from sklearn.metrics import mean_squared_error, r2_score

print("Mean Squared Error: ", mean_squared_error(y_test_numeric, y_pred))
print("R2 Score: ", r2_score(y_test_numeric, y_pred))

Mean Squared Error:  0.0018711627906976747
R2 Score:  0.9977954579278806


In [100]:
from sklearn.ensemble import RandomForestClassifier

rf_classifier = RandomForestClassifier(random_state=42)

rf_classifier.fit(X_train, y_train)

y_pred = rf_classifier.predict(X_test)

In [102]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

accuracy = accuracy_score(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Classification Report:\n", class_report)

Confusion Matrix:
 [[7219    0    4]
 [   0 2689    4]
 [   7    5 8347]]
Accuracy: 0.9989056087551299
Classification Report:
               precision    recall  f1-score   support

        High       1.00      1.00      1.00      7223
         Low       1.00      1.00      1.00      2693
      Medium       1.00      1.00      1.00      8359

    accuracy                           1.00     18275
   macro avg       1.00      1.00      1.00     18275
weighted avg       1.00      1.00      1.00     18275



In [112]:
conf_matrix = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)


Accuracy: 0.9989056087551299
Confusion Matrix:
 [[7219    0    4]
 [   0 2689    4]
 [   7    5 8347]]
Classification Report:
               precision    recall  f1-score   support

        High       1.00      1.00      1.00      7223
         Low       1.00      1.00      1.00      2693
      Medium       1.00      1.00      1.00      8359

    accuracy                           1.00     18275
   macro avg       1.00      1.00      1.00     18275
weighted avg       1.00      1.00      1.00     18275

